# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.13
  armv7: ghcr.io/home-assistant/armv7-base:3.13
  amd64-base: ghcr.io/home-assistant/amd64-base:3.13
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MIDIMonster"
  org.opencontainers.image.description: "Use MIDI devices in Home Assistant"
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  MIDIMONSTER_VERSION: "0.6"